# Generated by Django 5.2 on 2025-05-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_entity_id', models.CharField(max_length=255)),
                ('entity', models.CharField(max_length=255)),
                ('entity_id', models.CharField(max_length=255)),
                ('advisor_name', models.CharField(max_length=255)),
                ('entity_name', models.CharField(max_length=255)),
                ('role_id', models.CharField(max_length=255)),
                ('is_user_default', models.BooleanField(default=False)),
                ('al_client_id', models.CharField(max_length=255)),
                ('role_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_type', models.CharField(max_length=255)),
                ('entity_name', models.CharField(max_length=255)),
                ('profiles', models.ManyToManyField(related_name='users', to='app2.profile')),
            ],
        ),
    ]
