# Generated by Django 5.2 on 2025-05-04 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_sk', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('broker_dealer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id'], name='app_portfol_user_id_bb67b3_idx'), models.Index(fields=['number'], name='app_portfol_number_7d112c_idx')],
            },
        ),
    ]
