# Generated by Django 5.2 on 2025-05-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='event_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='event_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
